### ISSUE TITLE
Request for clarification on RNA-Seq data and gene annotations

### ISSUE THREAD

**Issue by Cold7** [MCorentin/Solanum_sitiens_assembly#1]
In our lab we are conducting research focused on drought resistance in tomato species.  Recently we were reviewing your paper, which presents a valuable de novo genome assembly for Solanum sitiens. we found your study highly relevant to my work, as it provides crucial insights into drought and salt tolerance mechanisms. Thank you for your valuable contribution to this field.

However, I have encountered the following challenges regarding the associated RNA-Seq data:

The sequence read data (SRR) lacks detailed annotations on the experimental conditions. Specifically, it is unclear which of the six samples correspond to control or treatment groups. Additionally, I was unable to locate the associated gene annotations in the NCBI database. So, could you please provide us  a clarification on the experimental conditions for the RNA-Seq samples (e.g., which samples are controls and which are treatments) and Information or access to the gene annotations associated with this study

Thank you very much for your time and assistance. I greatly appreciate your efforts in advancing this important area of study.

**Comment by MCorentin** [comment]
Hi, 

Thank you for your interest in the paper. 

We did not have cases and controls here. We sequenced multiple tissues from the plant in order to make a de-novo transcriptome assembly, representing most of the expressed genes (and aid gene prediction with Augustus).

The gene annotation for the predicted genes is available as a gff in this repository (here: https://github.com/MCorentin/Solanum_sitiens_assembly/blob/master/Augustus/augustus_annotations.gff). We annotated the predicted genes against **ITAG4.0** (annotation for _Solanum lycopersicum_, ids starting with _Solyc04g_) and **TAIR10** (_Arabidopsis thaliana_ annotation, ids starting with _AT1G_).

More files are available in this DropBox folder, if needed: https://www.dropbox.com/scl/fo/96pyatuj6e1zbz1fzknj4/ADjayIp9kmhOwI931pzy9kQ?rlkey=9b3rr5x3mv7oq6ktszi9shpey&e=1&dl=0

Let me know if anything is not clear.

Just in case, as it might be of interest to you, we have a similar paper on _Solanum chilense_, where we identified the probable dual role of some genes in drought resistance and fruit development: https://www.frontiersin.org/journals/plant-science/articles/10.3389/fpls.2024.1342739/full
